spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    password: mypass

  redis:
    host: localhost
    port: 6379

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 5m

logging:
  level:
    org:
      hibernate:
        transaction: DEBUG
        root: ERROR
      springframework:
        web: DEBUG
